name: Deploy to Sandbox

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ASIA4VT4N2G6ONG6RJEK
          aws-secret-access-key: LgvoQXu2F7yI7hkJetE+2AhQfFESmt6vcd94+pzi
          aws-region: us-west-2
          aws-session-token: FwoGZXIvYXdzEML//////////wEaDBHGfM51XtqbVbqeLSLAASPgpud2yfEalAP6RSKmXBLXoX62vctZw3wb2IU7KMpnQYuXRrmyIMtbSO5N1VWycvjKQNLSlN9UFmu0iUYgvPdRtelILPlGgGwSDzDCR4aK4OymWEAThatRWOANPgquXuhQJg1FCmgTaAcqxak2cFJzb+KBl34xe0lJGUz/WIklOSnShns1k8DjSe+GjnksoSR2L6urH0SX2wG9kHgcz1kxX+KUcb+rp38fL1an2bAyQ7424rQXJ1yV1FEMgsjg5SjNzPGfBjItpgMPuOEw7qxFtJ4ghtMYJFx0qKEE4I6p+Dwm/r8MSDHvYDNTYfxamkztS3qe

      - name: Upload index.html to S3 bucket
        run: |
          aws s3 cp index.html s3://neuefische1234567/index.html
