name: Deploy to Sandbox

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install AWS CLI
        uses: aws-actions/configure-aws-cli@v1
        with:
          aws-access-key-id: AKIAS6NTYUEE5HNFHYK3
          aws-secret-access-key: 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
          aws-region: us-west-2

      - name: Upload index.html to S3 bucket
        run: |
          aws s3 cp index.html s3://mygitbucket12345/index.html
