name: PushtoS3

on:
  push:
    branches:
    - main

jobs:
  pushtoS3:
    timeout-mins: 5
    runs-on: ubuntu-latest
    steps:
      - name: Upload to S3
        uses: jakejarvis/s3-sync-action@v0.5.3
        id: S3
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_session_token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws_region: eu-west-1
          src: Webseite/
          dest: s3://neuefische1234567/
          
